# **Singular-Value Decomposition**

Okapova Akerke

15BD02047

okapova.akerke@gmail.com

http://github.com/akerukesha

In [1]:
import numpy as np
from scipy.linalg import svd

In [44]:
# define a matrix
A = np.array([
    [3,1,1],
    [-1,3,1]
])
A

array([[ 3,  1,  1],
       [-1,  3,  1]])

In [45]:
# SVD
U, S, VT = svd(A)
print("U")
print(U)
print("S")
print(S)
print("VT")
print(VT)

U
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
S
[3.46410162 3.16227766]
VT
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [46]:
temp = A.dot(A.T)
S,U = np.linalg.eig(temp)
S = np.diag(np.sqrt(S))
VT = A.T.dot(U).dot(np.linalg.inv(S))
print("U")
print(U)
print("S")
print(S)
print("VT")
print(VT)

U
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
S
[[3.46410162 0.        ]
 [0.         3.16227766]]
VT
[[ 0.40824829 -0.89442719]
 [ 0.81649658  0.4472136 ]
 [ 0.40824829  0.        ]]


Sources:

https://towardsdatascience.com/my-notes-for-singular-value-decomposition-with-interactive-code-feat-peter-mills-7584f4f2930a

https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254